fit/gbm.R
munge/munge.R
munge/train-test.R

This code loops through the species and uses GBM to make predictions about the (Poisson-distributed) abundances.  It would take a while with 8 cores, so we should probably use Hipergator.

GBM prediction code

---

get_prism_data.R

This script only requires the file .data/bbs_data.csv, which is loaded inside forecasting-bbs-core.R , and the appropriate packages. 
If you source this script and run the command `bbs_bioclim=get_bioclim_data()`, it will do all the legwork of downloading prism data, extracting values, and calculating bioclim variables. It will also store bioclim and prism data in .data/bbsforecasting.sqlite to make things quicker in future calls.

Add bioclim

---

get_prism_data.R

1. Simplify the database connection code
2. Get rid of the old PostgreSQL code

Minor cleanup of database code in get_prism_data.R

---

forecast-bbs-core.R

Also cleans up an old comment and reruns the notebook following the move.

Move data extraction/processing code into core

---

forecast-bbs-core.R

Unless I screwed something up, I think I now have all the data and can actually start working on this :-)

BBS changed column names for latitude and longitude

---

forecast-bbs-core.R
get_elev_data.R
get_prism_data.R

Not sure what's going on with the merge commit, but I think we can just squash it when we merge.

specify dplyr namespace

---

.gitignore

I found these helpful for keeping my git log clean.

.gitignore data files

---

forecast-bbs-core.R

like #40, but with cleaner history

combine subspecies

---

R/forecast-bbs-core.R

Adds a new time-series regression model (linear regression with ARIMA errors) to the suite of time-series models.

Add dynamic regression modeling to time-series forecasts

---

R/forecast-bbs-core.R

General cleanup and restructuring of existing code to remove old analyses and shift code
from the notebook to the core R file.
Also adds a small amount of new exploratory analyses done with @davharris.

Analysis cleanup

---

R/forecast-bbs-core.R
R/get_prism_data.R
install-packages.R

Add/improve three spatial models of species richness including:
1. GAM with non-linear environmental responses
2. GAM with non-linear 2-D spatial responses
3. LME with site level effect
Results of a great morning of pair-programming with @davharris.

Modeling++

---

R/forecast-bbs-core.R

`get_richness_ts_env_data()` wasn't enforcing `min_num_years`. see #62

Fix min num years

---

R/forecast-bbs-core.R

enforce min_num_years after dropping sites with missing env data

---

R/get_elev_data.R

On my machine, the altitude files from `getData` were clogging up my working directory. I think this fixes it.

save altitude files in data folder, not in working directory

---

manuscript/draft.Rmd

merging this myself because Ethan already went over the changes with me

clarify discussion

---

manuscript/draft.Rmd
manuscript/important_references.Rmd

I put in a few comments, and also added a separate file to collect citations and how they are referenced. I used this idea in my other manuscript and think it works really well.

some comments and added citations

---

manuscript/draft.Rmd

This includes the Intro itself, a box that holds the list of things we've been talking about as good practices, and and initial try at a title.

Draft of Introduction

---

manuscript/draft.Rmd
manuscript/important_references.Rmd

some thoughts on modelling birds

Bird notes

---

R/forecast-bbs-core.R
install-packages.R

Updating the following for smooth reproducibility:
1. A number of new dependencies have been added that weren't added to `install-packages.R`
2. The Data Retriever and associated R package have had major new releases and associated changes in naming

Reproducibility update

---

DESCRIPTION
install-packages.R

I think this was missed before cause we all had the old retriever R packaged installed. After updating R and only installing the new package it complains.

change ecoretriever to rdataretriever

---

manuscript/draft.Rmd

I have incorportated everything from the early outline that I thought worked
reasonably well in the context of the paper as it has be developed. If folks
think there are crucial things from those bullets that should be put back in 
I'm happy to chat about it, but I didn't just miss them so let's start the conversation
with why you think they're important and where in the Discussion you think they
should go.

Draft of Discussion

---

R/post-observer.R
R/sdm-rf.R

1) Save a list of ARMIA coefficients so we can see how auto-arima plays out on the different site/year combinations with and without observer effects
2) Add an important group_by statement for the random forest models
Forgot to merge these before. Too many branches.

Minor analysis fixes

---

manuscript/draft.Rmd

I thought we needed something on our choice of yearly timesteps and it turned into this.

thoughts on our scale selection

---

R/observer_model.R
richness.job

minor hipergator changes

---

R/get_prism_data.R

This caused a lot of unneeded NA's in the final cmip bioclim dataset. See #133

WIP: fix na issue

---

manuscript/draft.Rmd
manuscript/refs.bib

This is a top to bottom revision of the ms. Major points of note:
* Completed expansion of Methods into prose
* Reworked flow of Results
* Recast @davharris's unnamed box item as 'Address unknown or unmeasured predictors'
* Added references throughout and created the bibtex file to go with them

Full ms revision

---

manuscript/draft.Rmd
manuscript/refs.bib

@ethanwhite I think all the discussion edits you did look good. I'd like to look at all the statements one more time when we have figures to look at. This is just fixing a few typos and adding in some more citation info.

Minor discussion edits

---

manuscript/draft.Rmd
manuscript/refs.bib

Let me know if these changes all make sense.

Revised methods and results

---

manuscript/draft.Rmd
manuscript/refs.bib

Addresses most of #142 but doesn't deal with the table request for CIMP5 or actually cite
the CIMP5 data since we haven't mentioned it in the paper yet.

Add citations and acknowledgements for code and data

---

analysis/fit-predict.R
analysis/serial_mistnet.R
mistnet.R

gbm wasn't parallel and was missing a `%>%`.
Mistnet was asking for too much memory and needed to be updated for the "future" predictions

Mistnet & bugfixes

---

manuscript/draft.Rmd

auto-arima model selections

---

manuscript/draft.Rmd

It's not perfect, but it's a start. Currently at 241 words.

First draft of abstract

---

analysis/cv-mistnet.R

I'd previously added this change to the wrong branch, apparently.

arguments for cv-mistnet.R

---

R/observer_model.R

This line was causing problems, and we don't actually need it.

minor deletion

---

manuscript/draft.Rmd

fix year counts (#165)

---

manuscript/draft.Rmd

Includes moving Table 1 into methods where the detail present in it makes more
sense. Replaces the reference to that table in the intro with a reference to
Figure 1, which works better there.

Editorial work on Intro

---

manuscript/draft.Rmd

Editorial work on Methods section

---

manuscript/draft.Rmd

Tweaks of Ethan's wording in 2 places

Minor wording suggestions

---

manuscript/draft.Rmd
manuscript/refs.bib

* Rework first 4 paragraphs back into 3 for better flow
* Combine two time-scale paragraphs and reduce emphasis on observed convergence
* Remove paragraph level headers and improve overall structure and flow instead
* Add reference for not being able to address imperfect detection
* General editorial work throughout
Fixes #185. Fixes #186.

Edits to Discussion

---

manuscript/draft.Rmd

(note that figure caption edits don't show up in the rich diff)

update figure captions

---

manuscript/draft.Rmd
manuscript/refs.bib

Also fix spelling of Dietze and a duplicate reference.

reference "notes": fix #180 

---

manuscript/refs.bib

I assume this is the correct paper?

add ward et al. to refs

---

manuscript/draft.Rmd

The biggest change here is for the way lead times are discussed. We don't really have evidence that the models' performance was converging, so I cut a lot of material there and tried to re-organize it in a bigger-picture way.

Discussion edits

---

manuscript/draft.Rmd
manuscript/refs.bib

* Citations
* Don't promise non-existent appendix

Minor pre-submission changes

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

do you think this will be enough for this comment? or should I add clarification in the manuscript?

clarify hindcasting to reviewer

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

I went thru and picked off the easiest ones. each commit addresses a single comment, or 2 related comments.

Clarify methods for reviewer r1

---

manuscript/reviewer_reply.Rmd

italics for reviewer comments, bold for our replies, headers in different sections.

markdown throughout the reviewer reply

---

figures/table.csv
manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

The fix to the title page never got merged when we submitted. This also fixes the table like Ward asked.

fix title page and table X's

---

manuscript/reviewer_reply.Rmd

This should make it easier to read, especially when rendered.

indent our responses

---

manuscript/reviewer_reply.Rmd

I spent a long time trying to get this right. I'm still not sure it's optimal, but I thought I'd see what you two thought.

Reviewer comments: spatial autocorrelation

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

make table 1 caption clearer

---

manuscript/draft.Rmd

An alternative to #219, which focuses on giving specific examples of where best practices were useful.

Add more specific results to the Abstract

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

This addresses the concerns of both the associate editor and Reviewer 2 about
the forecastability of BBS richness in the chosen time period. In adds a new
paragraph to the Discussion that expands on our previous discussion of these
points and calls for future research in this area.
Includes associated updates to the letter.
Alternative approach to #221.

Revise Discussion in response to questions about forecastability

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

Includes an alternative to #227

future predictions + brief abstract response

---

manuscript/draft.Rmd
manuscript/refs.bib
manuscript/reviewer_reply.Rmd

added 2 references and changed the intro wording a bit.

reply about deep time studies

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

Addresses Ward's comment about Line 329.

Reword sentence that used "forecast" three times in 13 words

---

manuscript/draft.Rmd
manuscript/reviewer_reply.Rmd

If we like this, I can add a comment for the reviewers.  
Ideally, we should also discuss where the standard deviations of ε come from, but that differs for the observer-corrected and non-corrected "average" models so I can't figure out the best way to discuss it without breaking the flow.

equations for baselines

---

manuscript/reviewer_reply.Rmd

Other peerj papers have this so I'm assuming we'll have one.

Reply intro

---

analysis/save-future.R

This creates the gzipped csv for zenodo

script to archive the forecasts
